import { test, expect } from "./fixtures";

test("new drafts use Nanum Myeongjo and supplemental font notice is acknowledged once", async ({ page }) => {
  const errors: string[] = [];
  page.on("pageerror", error => errors.push(error.message));
  await page.goto("/");
  const toolbar = page.getByRole("toolbar", { name: "Writing tools", exact: true });
  const font = toolbar.getByRole("combobox", { name: "Font family" });
  const body = page.getByRole("textbox", { name: "Document body" });
  await expect(font).toHaveValue("nanum-serif");
  await expect(font.locator('optgroup[label="Community fonts"] option')).toHaveCount(4);
  await expect(font.locator('optgroup[label="Writing fonts"] option')).toHaveCount(7);
  await body.fill("한글로 쓰는 즐거움. Writing with Wonboard.");
  await expect(body).toHaveCSS("font-family", /Nanum Myeongjo/);
  await page.screenshot({ path: "/private/tmp/wonboard-nanum-default.png" });
  await body.press("ControlOrMeta+a");
  for (const id of ["system", "dotum", "nanum-gothic"]) await font.selectOption(id);
  await expect(body.locator("span")).toHaveCSS("font-family", /Nanum Gothic/);
  expect(await page.evaluate(async () => (await document.fonts.load('20px "Nanum Gothic"', '한글')).length)).toBeGreaterThan(0);
  await expect(toolbar.getByRole("button", { name: "Got it" })).toHaveCount(0);
  await font.selectOption("soft");
  await expect(toolbar.getByRole("status")).toContainText("External communities may replace");
  await page.screenshot({ path: "/private/tmp/wonboard-font-notice-desktop.png" });
  await page.getByRole("button", { name: "Close Settings", exact: true }).click();
  await page.getByRole("button", { name: "Close document list", exact: true }).click();
  await page.setViewportSize({ width: 390, height: 844 });
  const noticeBox = await toolbar.getByRole("status").boundingBox();
  expect(noticeBox!.x).toBeGreaterThanOrEqual(0);
  expect(noticeBox!.x + noticeBox!.width).toBeLessThanOrEqual(390);
  await page.screenshot({ path: "/private/tmp/wonboard-font-notice-mobile.png" });
  await page.setViewportSize({ width: 1280, height: 720 });
  await toolbar.getByRole("button", { name: "Got it" }).click();
  await expect(page.getByRole("status").last()).toHaveText("Saved locally");
  await page.reload();
  await body.click();
  await body.press("ControlOrMeta+a");
  await font.selectOption("manrope");
  await expect(toolbar.getByRole("status")).toHaveCount(0);
  await page.getByRole("button", { name: "Preview", exact: true }).click();
  await expect(page.getByRole("dialog", { name: "Preview" }).locator(".preview-page")).toHaveCSS("font-family", /Nanum Myeongjo/);
  await page.getByRole("dialog", { name: "Preview" }).getByRole("button", { name: "Back to editor", exact: true }).click();
  await page.getByRole("combobox", { name: "Interface language" }).selectOption("ko");
  await page.evaluate(() => localStorage.removeItem("wonboard:supplemental-font-notice:v1"));
  const koreanToolbar = page.getByRole("toolbar", { name: "글쓰기 도구", exact: true });
  await koreanToolbar.getByRole("combobox", { name: "글꼴 선택" }).selectOption("serif");
  await expect(koreanToolbar.getByRole("status")).toContainText("글을 쓰는 즐거움");
  await page.screenshot({ path: "/private/tmp/wonboard-font-notice-korean.png" });
  await koreanToolbar.getByRole("button", { name: "알겠어요" }).click();
  expect(errors).toEqual([]);
});

test("toolbar and inspector share formatting and attachments work without the sidebar", async ({ page }) => {
  await page.goto("/");
  const body = page.getByRole("textbox", { name: "Document body" });
  const toolbar = page.getByRole("toolbar", { name: "Writing tools", exact: true });
  const inspector = page.getByRole("toolbar", { name: "Text formatting", exact: true });
  await body.fill("한글 English");
  await body.press("ControlOrMeta+a");
  await toolbar.getByRole("combobox", { name: "Font family" }).selectOption("serif");
  await toolbar.getByRole("button", { name: "Got it" }).click();
  await expect(inspector.getByRole("combobox", { name: "Font family" })).toHaveValue("serif");
  await inspector.getByRole("spinbutton", { name: "Text size (px)" }).fill("24");
  await inspector.getByRole("spinbutton", { name: "Text size (px)" }).press("Enter");
  await expect(toolbar.getByRole("spinbutton", { name: "Text size (px)" })).toHaveValue("24");
  await expect(body.locator("span")).toHaveCSS("font-size", "24px");
  await page.getByRole("button", { name: "Close Settings", exact: true }).click();
  await toolbar.getByRole("button", { name: "Center", exact: true }).click();
  await expect(body.locator("p")).toHaveCSS("text-align", "center");
  await toolbar.getByRole("button", { name: "Attachments", exact: true }).click();
  const attachments = page.getByRole("dialog", { name: "Attachments", exact: true });
  await expect(attachments.getByRole("textbox", { name: "YouTube or Vimeo URL" })).toBeVisible();
  await attachments.press("Escape");
  await expect(attachments).toHaveCount(0);
  await toolbar.getByRole("button", { name: "Selection settings", exact: true }).click();
  const settings = page.getByRole("dialog", { name: "Selection settings", exact: true });
  await settings.getByRole("button", { name: "Bold", exact: true }).click();
  await expect(body.locator("strong")).toHaveText("한글 English");
  await settings.getByRole("button", { name: "Close Settings", exact: true }).click();
  await expect(page.getByRole("complementary", { name: "Settings", exact: true })).toHaveCount(0);
  await toolbar.getByRole("button", { name: "Link", exact: true }).click();
  const link = page.getByRole("dialog", { name: "Link", exact: true });
  await link.getByRole("textbox", { name: "Link URL", exact: true }).fill("https://example.com/");
  await link.getByRole("button", { name: "Apply", exact: true }).click();
  await expect(body.locator("a")).toHaveAttribute("href", "https://example.com/");
  await page.getByRole("button", { name: "Close document list", exact: true }).click();
  await page.setViewportSize({ width: 390, height: 844 });
  await toolbar.getByRole("button", { name: "Attachments", exact: true }).click();
  await expect(attachments).toBeVisible();
  const toolbarBox = await toolbar.boundingBox();
  const panelBox = await attachments.boundingBox();
  expect(panelBox!.y).toBeGreaterThanOrEqual(toolbarBox!.y + toolbarBox!.height);
  expect(panelBox!.x).toBeGreaterThanOrEqual(0);
  expect(panelBox!.x + panelBox!.width).toBeLessThanOrEqual(390);
  expect(panelBox!.y + panelBox!.height).toBeLessThanOrEqual(844);
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true);
});

test("bundled fonts and inline sizes survive undo, save, preview and reload", async ({ page }) => {
  await page.goto("/");
  const body = page.getByRole("textbox", { name: "Document body" });
  const toolbar = page.getByRole("toolbar", { name: "Writing tools" });
  await expect(toolbar).toBeVisible();
  await expect(toolbar.getByRole("combobox", { name: "Font family" }).locator("option")).toHaveCount(11);
  await body.fill("한글 English");
  await body.press("ControlOrMeta+a");
  for (const [id, family] of [["serif", "Noto Serif KR Variable"], ["soft", "Gowun Dodum"], ["mono", "Nanum Gothic Coding"], ["noto-sans", "Noto Sans KR Variable"], ["nanum-serif", "Nanum Myeongjo"], ["gowun-serif", "Gowun Batang"], ["manrope", "Manrope Variable"], ["sans", "Pretendard Variable"]]) {
    await toolbar.getByRole("combobox", { name: "Font family" }).selectOption(id);
    if (id === "serif") await toolbar.getByRole("button", { name: "Got it" }).click();
    await expect(body.locator("span")).toHaveCSS("font-family", new RegExp(family));
    expect(await page.evaluate(async family => (await document.fonts.load(`24px "${family}"`, "English")).length > 0, family)).toBe(true);
  }
  await toolbar.getByRole("combobox", { name: "Font family" }).selectOption("serif");
  const size = toolbar.getByRole("spinbutton", { name: "Text size (px)" });
  await size.fill("24");
  await size.press("Enter");
  await expect(body.locator("span")).toHaveCSS("font-size", "24px");
  await toolbar.getByRole("button", { name: "Bold", exact: true }).click();
  await expect(body.locator("strong")).toHaveText("한글 English");
  await body.press("ControlOrMeta+z");
  await expect(body.locator("strong")).toHaveCount(0);
  await expect(page.getByRole("status").last()).toHaveText("Saved locally");
  await page.reload();
  await expect(body.locator("span")).toHaveCSS("font-family", /Noto Serif KR Variable/);
  await expect(body.locator("span")).toHaveCSS("font-size", "24px");
  await page.getByRole("button", { name: "Preview", exact: true }).click();
  const preview = page.getByRole("dialog", { name: "Preview" });
  await expect(preview.locator(".tiptap span")).toHaveText("한글 English");
  await expect(preview.locator(".tiptap span")).toHaveCSS("font-size", "24px");
});

test("clear formatting works at the cursor, preserves links and supports undo and partial selection", async ({ page }) => {
  await page.goto("/");
  const body = page.getByRole("textbox", { name: "Document body" });
  const toolbar = page.getByRole("toolbar", { name: "Writing tools", exact: true });
  await body.fill("Hello world");
  await body.press("ControlOrMeta+a");
  await toolbar.getByRole("combobox", { name: "Font family" }).selectOption("gowun-serif");
  await toolbar.getByRole("button", { name: "Got it" }).click();
  await toolbar.getByRole("button", { name: "Bold", exact: true }).click();
  await toolbar.getByRole("button", { name: "Link", exact: true }).click();
  const link = page.getByRole("dialog", { name: "Link", exact: true });
  await link.getByRole("textbox", { name: "Link URL" }).fill("https://example.com/");
  await link.getByRole("button", { name: "Apply", exact: true }).click();
  await body.press("ArrowRight");
  await toolbar.getByRole("button", { name: "Clear text formatting", exact: true }).click();
  await expect(body.locator("span, strong")).toHaveCount(0);
  await expect(body.locator("a")).toHaveText("Hello world");
  await body.press("ControlOrMeta+z");
  await expect(body.locator("strong")).toHaveText("Hello world");
  await expect(body.locator("span")).toHaveCSS("font-family", /Gowun Batang/);
  await body.press("ControlOrMeta+a");
  await body.press("ArrowLeft");
  for (let i = 0; i < 5; i++) await body.press("Shift+ArrowRight");
  expect(await page.evaluate(() => window.getSelection()?.toString())).toBe("Hello");
  await toolbar.getByRole("button", { name: "Clear text formatting", exact: true }).click();
  await expect(body.locator("strong")).toHaveText(" world");
  await expect(body).toHaveText("Hello world");
  await expect(body.locator("a")).toHaveAttribute("href", "https://example.com/");
});

test("Markdown input still produces headings, lists and inline marks", async ({ page }) => {
  await page.goto("/");
  const body = page.getByRole("textbox", { name: "Document body" });
  await body.click();
  await body.pressSequentially("## Heading");
  await expect(body.locator("h2")).toHaveText("Heading");
  await body.press("Enter");
  await body.pressSequentially("**bold** and *italic*");
  await expect(body.locator("strong")).toHaveText("bold");
  await expect(body.locator("em")).toHaveText("italic");
  await body.press("Enter");
  await body.pressSequentially("- List");
  await expect(body.locator("ul li")).toContainText("List");
  await body.press("Shift+Enter");
  await body.pressSequentially("next line");
  await expect(body.locator("ul li br")).toHaveCount(1);
});
