import { test, expect } from "@playwright/test";
import { syntheticPng } from "../helpers/sites-runtime";

const owner = { "X-Wonboard-Test-User": "owner-fixture", Origin: "http://127.0.0.1:5174" };
test.beforeEach(async ({ request, context }) => {
  expect((await request.post("/__sites-test/reset")).status()).toBe(204);
  await context.setExtraHTTPHeaders(owner);
  expect((await request.post("/api/sites/setup", { headers: owner, data: { accepted: true, locale: "en" } })).status()).toBe(200);
});
test("shared writing stays frozen until library update, then revokes independently", async ({ page, browser }, testInfo) => {
  const errors: string[] = [];
  page.on("pageerror", error => errors.push(error.message));
  await page.setViewportSize({ width: 1440, height: 900 });
  await page.goto("/");
  await page.getByRole("textbox", { name: "Add title" }).fill("First frozen title");
  await page.getByRole("textbox", { name: "Document body" }).fill("Independent writing");
  await page.getByRole("tab", { name: "Attachments 0", exact: true }).click();
  await page.locator('.attachments-panel input[type="file"]').setInputFiles({ name: "photo.png", mimeType: "image/png", buffer: syntheticPng });
  await expect(page.locator(".tiptap .wb-media img")).toHaveCount(1);
  await page.getByRole("button", { name: "Export", exact: true }).click();
  const exporting = page.getByRole("dialog", { name: "Export", exact: true });
  await exporting.getByRole("checkbox").check();
  await exporting.getByRole("button", { name: "Create shared writing snapshot", exact: true }).click();
  const address = exporting.getByRole("textbox", { name: "Shared writing URL", exact: true });
  await expect(address).toBeVisible();
  const url = await address.inputValue(), anonymous = await browser.newContext();
  const viewer = await anonymous.newPage(); viewer.on("pageerror", error => errors.push(error.message));
  try {
    await viewer.goto(url);
    await expect(viewer.getByRole("heading", { name: "First frozen title" })).toBeVisible();
    await expect.poll(() => viewer.locator("img").evaluate((img: HTMLImageElement) => img.naturalWidth)).toBe(1);
    const oldAsset = await viewer.locator("img").getAttribute("src");
    await exporting.getByRole("button", { name: "Close", exact: true }).click();
    await page.getByRole("textbox", { name: "Add title" }).fill("Updated frozen title");
    await expect(page.getByText("Saved to my Site", { exact: true })).toBeVisible();
    await viewer.reload();
    await expect(viewer.getByRole("heading", { name: "First frozen title" })).toBeVisible();
    await page.locator(".writing-library").getByRole("button", { name: "File library", exact: true }).click();
    const library = page.getByRole("dialog", { name: "File library", exact: true });
    await library.getByRole("button", { name: "Distributed copies", exact: true }).click();
    const writing = library.getByRole("region", { name: "Shared writing", exact: true });
    page.once("dialog", dialog => dialog.accept());
    await writing.getByRole("button", { name: "Update from saved draft", exact: true }).click();
    await expect(writing.locator("strong")).toHaveText("Updated frozen title");
    await viewer.reload();
    await expect(viewer.getByRole("heading", { name: "Updated frozen title" })).toBeVisible();
    expect((await anonymous.request.get(new URL(oldAsset!, url).href)).status()).toBe(200);
    await writing.getByRole("button", { name: "Revoke link", exact: true }).click();
    await expect(writing.getByText("Revoked or expired", { exact: true })).toBeVisible();
    expect((await anonymous.request.get(url)).status()).toBe(404);
    expect((await anonymous.request.get(new URL(oldAsset!, url).href)).status()).toBe(404);
    await writing.getByRole("button", { name: "Issue new link", exact: true }).click();
    await expect(writing.getByText("Link active", { exact: true })).toBeVisible();
    const renewed = await writing.getByRole("textbox", { name: "Shared writing URL", exact: true }).inputValue();
    expect(renewed).not.toBe(url); await viewer.goto(renewed);
    await expect.poll(() => viewer.locator("img").evaluate((img: HTMLImageElement) => img.naturalWidth)).toBe(1);
    await page.screenshot({ path: testInfo.outputPath("snapshot-library-desktop.png") });
    await page.setViewportSize({ width: 390, height: 844 });
    await page.screenshot({ path: testInfo.outputPath("snapshot-library-mobile.png") });
    expect(await library.evaluate(node => node.scrollWidth <= node.clientWidth)).toBe(true);
    await library.getByRole("button", { name: "Close", exact: true }).click();
    await page.getByRole("combobox", { name: "Interface language" }).selectOption("ko");
    await page.locator(".writing-library").getByRole("button", { name: "파일 보관함", exact: true }).click();
    const korean = page.getByRole("dialog", { name: "파일 보관함", exact: true });
    await korean.getByRole("button", { name: "배포한 항목", exact: true }).click();
    await expect(korean.getByRole("heading", { name: "공유 글", exact: true })).toBeVisible();
    await page.screenshot({ path: testInfo.outputPath("snapshot-library-ko-mobile.png") });
    expect(await korean.evaluate(node => node.scrollWidth <= node.clientWidth)).toBe(true);
    await page.keyboard.press("Escape");
    await expect(korean).toHaveCount(0);
    expect(errors).toEqual([]);
  } finally { await anonymous.close(); }
});
